apiVersion: granular-deployment.dekinci.com/v1alpha1
kind: VirtualDeployment
metadata:
  name: demo-shop-product-vd
  namespace: gd-demo-shop
spec:
  versions:
    - v1
  deployment:
    replicas: 1
    selector:
      matchLabels:
        app: demo-shop-product
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: demo-shop-product
      spec:
        containers:
          - image: 10.0.10.1:5000/gd-demo-shop-product
            imagePullPolicy: Always
            name: shop-product
            ports:
              - containerPort: 8080
            readinessProbe:
              failureThreshold: 5
              httpGet:
                path: /actuator/health
                port: 8080
              periodSeconds: 5
              successThreshold: 2
              timeoutSeconds: 3
              initialDelaySeconds: 30
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /actuator/health
                port: 8080
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 3
              initialDelaySeconds: 30
            resources:
              requests:
                cpu: 300m
                memory: 512Mi
              limits:
                cpu: 800m
                memory: 1Gi