kind: Namespace
apiVersion: v1
metadata:
  name: gd-demo-shop
  labels:
    istio-injection: enabled

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: gd-demo-shop
  name: demo-shop-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - gd-shop.i.dknc.io
---
